"""Model hyperparameters and classification defaults."""

RF_NUM_TREES = 150
RF_MAX_DEPTH = 12
RF_MIN_SAMPLES_SPLIT = 2
RF_MIN_SAMPLES_LEAF = 1
RF_ENABLE_OOB_SCORE = False
RF_CLASS_WEIGHT = "balanced_subsample"
RF_TOP_FEATURE_IMPORTANCES = 20

BRF_NUM_TREES = 100
BRF_MAX_DEPTH = None
BRF_MIN_SAMPLES_SPLIT = 2
BRF_MIN_SAMPLES_LEAF = 1
BRF_ENABLE_OOB_SCORE = False

SVM_KERNEL = "rbf"
SVM_C = 1.0

XGB_NUM_ESTIMATORS = 200
XGB_LEARNING_RATE = 0.1
XGB_MAX_DEPTH = 6
XGB_ADAPTIVE_ESTIMATORS_ENABLED = True
XGB_GUARDRAIL_MEDIUM_CLASS_THRESHOLD = 25
XGB_GUARDRAIL_LARGE_CLASS_THRESHOLD = 60
XGB_GUARDRAIL_MEDIUM_ESTIMATOR_CAP = 180
XGB_GUARDRAIL_LARGE_ESTIMATOR_CAP = 120
XGB_GUARDRAIL_MEDIUM_EARLY_STOPPING = 15
XGB_GUARDRAIL_LARGE_EARLY_STOPPING = 10
XGB_GUARDRAIL_PROFILE_CAPS = {}

LR_MAX_ITER = 2000
LR_SOLVER = "lbfgs"

INCLUDE_CONFIDENCE_SCORES = True
DEFAULT_LABEL_FORMAT = "structured"
SUPPORTED_LABEL_FORMATS = [
    "structured",
    "canonical",
    "tags",
    "vector",
    "compact",
    "enriched",
    "json",
]
CLASSIFICATION_TERMINAL_COMPACT = True
CLASSIFICATION_PREVIEW_ROWS = 8
CLASSIFICATION_EXPORT_PREVIEW_ROWS = 0

ENABLE_SMOTE_OVERSAMPLING = True

DEFAULT_TRAINING_MODELS = [
    "random_forest",
    "balanced_random_forest",
    "xgboost",
    "logistic_regression",
]
ENABLE_BENCHMARK_MODELS = True
BENCHMARK_TRAINING_MODELS = [
    "random_forest",
    "balanced_random_forest",
    "xgboost",
    "logistic_regression",
]

MIN_SAMPLE_COUNT_FOR_MODEL = 25
MIN_FAMILY_SUPPORT = 3
GROUP_LOW_SUPPORT_LABELS = False
ENABLE_AGGRESSIVE_LEAKAGE_PRUNING = False
LOW_CONFIDENCE_THRESHOLD = 0.30
ENABLE_LOW_CONFIDENCE_ABSTAIN = False
ABSTAIN_LABEL = "other"
ALLOW_PREDICTION_DB_FAMILY_OVERRIDE = False
