"""Parser quality gate thresholds."""

PARSER_UNKNOWN_EXCLUDE_THRESHOLD = 0.70
PARSER_MAPPED_MIN_THRESHOLD = 0.30
PARSER_GENERIC_DOWNWEIGHT_THRESHOLD = 0.60
PARSER_GENERIC_DOWNWEIGHT_FACTOR = 0.50
PARSER_MIN_INCLUDED_VENDORS = 8
PARSER_ALLOW_RELAXED_MAPPED_GATE = True
